### ISSUE TITLE
Workout Creation & Modification

### ISSUE THREAD

**Issue by dtom90** [dtom90/Gains#11]
This epic embodies the full lifecycle of workout objects. This includes:
- [x] Workout name
- [x] Exercise list
- [ ] Target weight, reps & sets per exercise
- [ ] Rest between sets
- [ ] Record of modifications (to exercises or targets)
